version: '3'

services:

  sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server
    ports:
      - 1433:1433
    volumes:
      - sql-server-data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Test1234
      - MSSQL_PID=Express

volumes:
  sql-server-data:
